### ISSUE TITLE
`AngularFireAuth.authState` does not fire

### ISSUE THREAD

**Issue by sarunint** [angular/angularfire#2309]
### Version info

**Angular:** 8.2.14

**Firebase:** 7.8.0

**AngularFire:** 5.4.0-5.4.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**: https://stackblitz.com/edit/angular-lgfgbl

**Steps to set up and reproduce**
1. Fill your Firebase config in `app.module.ts`
2. Run
3. Click "Sign in with Google"

**Sample data and security rules**: none
### Debug output

** Errors in the JavaScript console **: none

** Output from `firebase.database().enableLogging(true);` **: not applicable

** Screenshots **

### Expected behavior

After redirected back from sign-in, you should be automatically to `/main` path.

### Actual behavior

The app does not redirect you to `/main` path. (It does in `@angular/fire@5.3.1`.)

### My observation

If I remove the line `this.user$ = this.afa.authState;` out from `app.component.ts`, it works! Doesn't know why.

**Comment by techn1fire** [comment]
Same issue here. Seems to fire randomly, or after a few seconds during testing.

**Comment by JoshuvaGeorge03** [comment]
I do having this issue, how to fix this?

**Comment by FlexWilliams** [comment]
Seeing same issue with the authState observable not being fired when subscribed to.

Just upgraded:
firebase 6.5.0 to 7.8.0
@angular/fire 5.2.1 to 5.4.0

**Comment by Benny739** [comment]
Same issue here.

**Comment by HoverAlex** [comment]
Same here :D

**Comment by jamesdaniels** [comment]
Should be addressed in `5.4.1`, sorry for the regression. Please reopen if you're still having trouble after upgrading.

**Comment by sarunint** [comment]
It does not fix this 😉. That's the reason why this issue and #2307 are separated.

**Comment by sarunint** [comment]
@jamesdaniels It seems that I can't reopen this issue. Lol

**Comment by sarunint** [comment]
I've been able to create a simpler reproduction here: https://stackblitz.com/edit/angular-bk3qb6

**Comment by jamesdaniels** [comment]
Great I can repro here. `.user` seems to work as expected and even more bafflingly... if you copy/paste the source for `. authState` it seems to work as expected.

**Comment by sarunint** [comment]
I've also noticed that changing to `.user` solves the problem.

But, if you change both `.authState` to `.user`, the problem still exists.

![image](https://user-images.githubusercontent.com/3850197/73906957-402bc400-48d7-11ea-9037-3a182533ba4e.png)

I think this is may be due to how both fields is constructed.

https://github.com/angular/angularfire/blob/168077b669a53385ce67be29df5169d6cbdef07a/src/auth/auth.ts#L50-L56

I'm thinking `ReplaySubject` might work here...

**Comment by jamesdaniels** [comment]
Just killed my last comment since I've found the root cause. It seems something about the new Zone refactors is breaking multiplexing.

**Comment by jamesdaniels** [comment]
It seems to be forcing a share, where one shouldn't exist, even if you use a different factory. This came up in review but I thought it was addressed.

**Comment by jamesdaniels** [comment]
Since it's shared without reply, the second subscribe gets no result; since it's not creating a new observable. If I don't have a fix quickly I'll revert the zone memory leaks in a patch. Thanks so much for catching this!

**Comment by jamesdaniels** [comment]
Demonstrating the break here https://stackblitz.com/edit/angular-7kb1uf?file=src%2Fapp%2Fapp.component.ts

**Comment by JoshuvaGeorge03** [comment]
This issue still present in 5.4.1 also.

**Comment by jamesdaniels** [comment]
Fixed in `5.4.2`

**Comment by FlexWilliams** [comment]
Updating to 5.4.2, looks fixed on my end, running:

"@angular/fire": "^5.4.2",
"firebase": "^7.8.0",

**Comment by ErraticFox** [comment]
I'm having this same trouble with 
```js
 this.afAuth.authState.pipe(
      switchMap(user => {
        return user ? of(user) : of(null)
      })
    )
```
and when I sign in successfully (shown by the promise) and then log `this.$user)` it outputs `null`.

**Comment by ckrandhir** [comment]
I think it not working in "@angular/fire": "^6.0.0". Could you please look into this?
