### ISSUE TITLE
[Analytics 6.0.0-rc.1] APP_VERSION and APP_NAME example

### ISSUE THREAD

**Issue by vandres** [angular/angularfire#2340]
### Version info

**Angular: 9.0.4**

**Firebase: 7.9.3**

**AngularFire: 6.0.0-rc.1**

### How to reproduce these conditions

I am having setup AngularFire with Analytics and the tracking works as expected. But the values for Version and Name are always empty. Am I configuring it wrong?

<img width="458" alt="grafik" src="https://user-images.githubusercontent.com/1436383/75631653-b6d18e00-5c05-11ea-81df-e02026ba494c.png">

### Expected behavior

APP_VERSION and APP_NAME appear in Analytics 

### Actual behavior

APP_VERSION and APP_NAME are empty

**Comment by vandres** [comment]
In the Firebase DebugStream I can see app_version arriving

<img width="689" alt="grafik" src="https://user-images.githubusercontent.com/1436383/75633059-eb981200-5c12-11ea-8d01-aa603bb79557.png">

Latest Release still is empty

<img width="1256" alt="grafik" src="https://user-images.githubusercontent.com/1436383/75633076-01a5d280-5c13-11ea-82dd-ea74ac44c222.png">

**Comment by EdricChan03** [comment]
IIRC, the data should take a day or more to update, so I suggest that you should check the data the following day.

**Comment by vandres** [comment]
It is online for days

**Comment by jamesdaniels** [comment]
I've noticed too that my app name and version are not showing up in the console. When I added this integration I was [going off the gtag `screen_view` docs](https://developers.google.com/analytics/devguides/collection/gtagjs/screens#screen_view_parameters). This seems like a bug with either the underlying Google Analytics integration or the Firebase Console, [please open a bug](https://firebase.google.com/support/troubleshooter/report/bugs) & I will push from my side too.

I'll leave this open for discussion or the possibility that the analytics integration is working improperly.

**Comment by vandres** [comment]
Got reply from Firebase

Thanks for reaching out!
 

> I would like to inform you that there is an ongoing issue with latest release on our end, which may also affect the app_version and app_name reports. Our engineers are actively working on its fix. We are yet to find out any details or timelines as to when it will be fixed. For now, you can check our release notes for any updates about Firebase features and its services. Apologies for any inconvenience this may have caused you.
>  
> Let me know if there is something else I can help you with.

**Comment by jamesdaniels** [comment]
This should be addressed now.

**Comment by elinake** [comment]
@jamesdaniels Can you refer which version of AngularFire / Firebase this issue is fixed? I'm still experiencing the same exact issue, app_version is sent and logged but after multiple days latest release and adding comparison based on app version are still empty. I have Angular fire 7.2.1 and firebase 9.6.6.

**Comment by patricsteiner** [comment]
Still seems to be an issue. APP_NAME still is not available on my analytics page after setting it up as a provider in appmodule:
``` 
   {
      provide: APP_NAME,
      useValue: 'myApp
    },
```

**Comment by zogral** [comment]
Using the latest @Angular/fire 7.x, how is it possible to import APP_NAME, APP_VERSION and CONFIG without relying on the compat package?

Currently I only found those values here `import { APP_VERSION, APP_NAME, CONFIG } from '@angular/fire/compat/analytics';`, but everything else related to Firebase is importing using the new `'@angular/fire/analytics'` schema.

Did you manage to solve this @patricsteiner / @elinake ?

**Comment by patricsteiner** [comment]
@zogral You are right, I noticed later that the APP_NAME etc. are imported from the compat package.... I couldn't find a working solution yet :(

**Comment by elinake** [comment]
@zogral This page https://github.com/angular/angularfire/blob/master/docs/analytics/getting-started.md directs to import everything related to analytics from compat module. I don't think it has anything to do with APP_VERSION not logged correctly.
